import oracledb

# oracledb.init_oracle_client(lib_dir=None) 

username = 'SYS'
password = 'Database07'
host = '8.153.175.232'
port = 1521
service_name = 'FREE'

dsn = f"{host}:{port}/{service_name}"

try:
    conn = oracledb.connect(user=username, password=password, dsn=dsn, mode=oracledb.SYSDBA)
    cursor = conn.cursor()

    # 先删表
    cursor.execute("""
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE test_table';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
          RAISE;
        END IF;
    END;
    """)

    # 再建表
    cursor.execute("""
    CREATE TABLE test_table (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50),
        age NUMBER
    )
    """)
    print("表创建成功")

    # 插入几条数据
    cursor.executemany("INSERT INTO test_table (name, age) VALUES (:1, :2)", [
        ("YSJ", 230),
        ("Bob", 30),
        ("Cindy", 28)
    ])
    conn.commit()
    print("数据插入成功")

    # 查询
    cursor.execute("SELECT id, name, age FROM test_table")
    for row in cursor:
        print(row)

except Exception as e:
    print("出错: ", e)

finally:
    if 'cursor' in locals():
        cursor.close()
    if 'conn' in locals():
        conn.close()
