/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'coupon-management',
    path: '/coupon-management',
    component: 'layout.base$view.coupon-management',
    meta: {
      title: 'coupon-management',
      i18nKey: 'route.coupon-management',
      icon: 'mdi:ticket-percent',
      order: 3
    }
  },
  {
    name: 'goods-management',
    path: '/goods-management',
    component: 'layout.base$view.goods-management',
    meta: {
      title: 'goods-management',
      i18nKey: 'route.goods-management',
      icon: 'mdi:storefront',
      order: 2
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'order-management',
    path: '/order-management',
    component: 'layout.base$view.order-management',
    meta: {
      title: 'order-management',
      i18nKey: 'route.order-management',
      icon: 'mdi:clipboard-list',
      order: 4
    }
  },
  {
    name: 'profile',
    path: '/profile',
    component: 'layout.base$view.profile',
    meta: {
      title: 'profile',
      i18nKey: 'route.profile',
      icon: 'mdi:account-circle',
      order: 5
    }
  }
];
